// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyhuqbosxspxvmocoozo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95aHVxYm9zeHNweHZtb2Nvb3pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NTgzNzcsImV4cCI6MjA1OTMzNDM3N30.Xljycl93zB2TGFw8nNCYiqhC0JPAqNx6vuBR6XYQdmQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);